version: "2"
services:
  hadoop_master:
    build: master
    ports:
     - "8088:8088"
     - "50070:50070"
     - "50075:50075"
     - "19888:19888"
    volumes:
     - ./master/configuration_files:/usr/local/hadoop/etc/hadoop
  hadoop_slave:
    build: slave 
    volumes:
     - ./slave/configuration_files:/usr/local/hadoop/etc/hadoop